### ISSUE TITLE
No Licence

### ISSUE THREAD

**Issue by turtles2** [sourabh14/network-mapper#1]
This Project lacks a license could you add one? I may want to include portions of this in [my project](https://github.com/turtles2/WISPBill) and I can't do that unless you include a licence.

**Comment by turtles2** [comment]
I have to say that I like this software so far. I think it is just what I need. Could you please let me know if I can use it?

**Comment by sourabh14** [comment]
Sorry for the late reply. I'll let you know when we're ready for public release.
